version: '3.4'

services:
  quail-dev:
    image: ${QUAIL_DEV_IMAGE}
    container_name: quail-dev
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30103:5000"
    volumes:
      - ../../quail/pavics-component/wps.cfg:/wps.cfg
      - wps_outputs:/data/wpsoutputs
      - /tmp
    restart: always

  magpie:
    volumes:
    - ../../quail/pavics-component/quail-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/quail-magpie-permission.cfg:ro
    - ../../quail/pavics-component/quail-magpie-provider.cfg:/opt/local/src/magpie/config/providers/quail-magpie-provider.cfg:ro

  proxy:
    volumes:
      - ../../quail/pavics-component/quail_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/quail_canarie_api_monitoring.py:ro